# Generated by Django 5.2.3 on 2025-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_successful', models.BooleanField(default=False)),
                ('anomaly_flag', models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('checkpoint', 'Checkpoint'), ('blocked', 'Blocked'), ('new_ip', 'New Ip Detected')], default='normal', max_length=100)),
            ],
        ),
    ]
